### ISSUE TITLE
Foreign characters in different encoding than utf-8 cause it to crash

### ISSUE THREAD

**Issue by autrimpo** [markjones112358/dmenu-extended#12]
When trying to add files which contain foreign characters in different encoding than utf-8, dmenu-extended simply crashes.
After some debugging I managed to identify the issue and remove the files.
It would be nice if dmenu-extended would ignore the files and print a warning, or at least print why and on which file it crashed.
Example of files which will cause it to crash:
http://www.serialzone.cz/download/titulky-serie/?sid=54&serie=2

Also including program output

Traceback (most recent call last):
  File "/usr/bin/dmenu_extended_run", line 11, in <module>
    dmenu_extended.run(debug)
  File "/usr/lib/python3.4/site-packages/dmenu_extended.py", line 1084, in run
    cache = d.cache_load()
  File "/usr/lib/python3.4/site-packages/dmenu_extended.py", line 501, in cache_load
    if self.cache_regenerate() == False:
  File "/usr/lib/python3.4/site-packages/dmenu_extended.py", line 468, in cache_regenerate
    cache = self.cache_build()
  File "/usr/lib/python3.4/site-packages/dmenu_extended.py", line 788, in cache_build
    self.cache_save(foldernames, file_cache_folders)
  File "/usr/lib/python3.4/site-packages/dmenu_extended.py", line 478, in cache_save
    f.write(item+"\n")
  File "/usr/lib/python3.4/codecs.py", line 711, in write
    return self.writer.write(data)
  File "/usr/lib/python3.4/codecs.py", line 368, in write
    data, consumed = self.encode(object, self.errors)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udca1' in position 58: surrogates not allowed

**Comment by markjones112358** [comment]
Oh no, that's not good.
I have the feeling a recent change made to the character encoding and filtering may have affected this.
I'm hoping @SparklePigBang may be able to shed some light on this as he seems to have a deeper understanding of how this works. We did have more verbose output on events such as this and would indeed skip troublesome entries.

Are you able to respond with a textual list of the filenames, rather than linking to a zip?

**Comment by SparklePigBang** [comment]
Unfortunately, detecting the encoding of a file in general is pretty much impossible. Files usually don't specify it explicitly, so the only way is to do it heuristically - i.e. look at the contents of the file and see which language it looks like. This is of course not always accurate.

The recent changes I made the assumption that files are always encoded using the system encoding (usually `utf-8` on Linux systems). It seems that's not a good assumption to make.

Now, there is a Python library called [`chardet`](https://pypi.python.org/pypi/chardet "Chardet Python Library"), which will try to detect the encoding of a file. But it's not a standard library, and it seems silly to require installing an external library just for this (though I guess it could be made an optional feature, with a `try import chardet`).

It seems the best alternative is to catch `UnicodeEncodeError`s as before. Unfortunately, this will only work when Python actually realises the encoding is wrong, so some files may slip through; this seems unavoidable however.

I can get a pull request ready tomorrow (in the UK), if you like.

**Comment by markjones112358** [comment]
Hey, great!
The encoding of the file itself isn't of concern, in this users case it was a folder anyway.
Catching the error and omitting the troublesome results has worked well in the past. This also gave the opportunity to print out the files/paths that were causing the problem.
Don't rush for anything, just when you've got some time.

Much appreciated.

**Comment by autrimpo** [comment]
@SparklePigBang 
As @markjones112358 has said, it's not the contents of the file, it's the filename that is the problem.
Reading my first post again, I can see why this could be misunderstood.

@markjones112358 
Sure, here's the problematic directory from the zip as it appears on my system:

Ostatn+�/

**Comment by SparklePigBang** [comment]
My mistake! I was mixing up with the application file cache, which does read the contents of files.

Since the filename is the problem, using a heuristic library makes even less sense, and the only option will be to catch Unicode errors. I'll do this now.

**Comment by SparklePigBang** [comment]
I've found a nice solution. Rather than ignoring troublesome items, it simply replaces troublesome characters with question marks.

@markjones112358 
There are a few alternatives to this method, as given in the table [here](https://docs.python.org/2/library/codecs.html#codec-base-classes "Python Codec Modules Base Classes"). Alternatively, I could completely ignore troublesome entries, if you like.

@autrimpo 
Does this work for you?

(Sorry for the double commit; I pushed to another branch by mistake, and Github seems to be holding on to that commit, even though I removed it.)

**Comment by autrimpo** [comment]
I'm not sure if you're asking if the fixed version works for me, or if the proposed solution is ok, so I'll answer both.
Your version indeed does not crash and successfully builds the cache.
As to the replacing of characters, since my particular case was a directory with files I would not acces through dmenu (subtitles), it does not really matter what happens to it as long as it can build the cache. But that made me wonder, how would this act if I wanted to open the files? Wouldn't it cause problems (since the path in cache is different from the actual path)?

**Comment by markjones112358** [comment]
Not that I'm aware of. 
![screenshotmenuchars](https://cloud.githubusercontent.com/assets/3971384/5620653/b06b53dc-9592-11e4-8faa-1ae27a6a1078.png)
The top entry is the zip file content, the lower is the copy-paste from your earlier post. When executed they both open their intended locations.

Ah, its Python 2 that causes the issue! If you run it with Python 3 there is no problem.
This will require a bit of time for me to get any further with, something I don't have a lot of right now. If you're okay using SparklePigBang's fix for now we can work on something more long term.

**Comment by autrimpo** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/5968483/5621278/4f879d9a-9534-11e4-88f3-0562a801fef7.png)
Seeing that the unpacked files on your system were different from mine, I installed Gnome file-roller and unpacked the zip with that and the result was the same as yours. Seems that aunpack is the one that can't deal with the name and spits out garbage.

Sorry for not checking this before submitting a bug and wasting your (and @SparklePigBang's) time.

**Comment by markjones112358** [comment]
Think nothing of it. Ideally, dmenu-extended would handle the issue gracefully so we never ended up here in the first place. Glad it's sorted.
Nice setup by the way.

*Note to future self* (or interested third-parties):
Detect `UnicodeEncodeError` when writing to cache. On detection, start again writing the cache line-by-line and skip erroneous results entirely (giving the appropriate output to console).

Thanks @SparklePigBang for your input.

**Comment by SparklePigBang** [comment]
Good stuff
