### ISSUE TITLE
FileNotFoundError on startup

### ISSUE THREAD

**Issue by javaguirre** [markjones112358/dmenu-extended#15]
Hi! I tried to start it, but an exception is thrown, I haven't had time to get into the code to check what could it be.

![1424458230](https://cloud.githubusercontent.com/assets/488556/6307147/d613c43c-b939-11e4-91b1-747cb93eeb0a.png)

I used the package in [aur](https://aur.archlinux.org/packages/dmenu-extended/) and master from this repo.

Thank you!

**Comment by markjones112358** [comment]
Thanks for the traceback!
I updated dmenu-extended to stop this happening so either installation method should work now.
Let me know if you have any other issues.

**Comment by javaguirre** [comment]
I don't see any new changes, where should I look?

**Comment by markjones112358** [comment]
So sorry, I forgot to push the changes. Try again. This repo and the AUR package are up-to-date now.

**Comment by markjones112358** [comment]
Hi Javaguirre, have you had a chance to check if this fixed your issue?
The issue was related to your system path having an extra delimeter, which dmenu-extended now ignores before searching for binaries.

**Comment by vanishing** [comment]
I'm afraid not...
```
OSError: [Errno 2] No such file or directory: '/usr/lib/lightdm/lightdm'
```

**Comment by markjones112358** [comment]
Are you able to provide a full traceback for this error?

**Comment by vanishing** [comment]
Here's the traceback:
```
Setting up dmenu-extended prefs files...
Plugins directory exists - skipped
Cache directory exists - skipped
prefs directory exists - skipped
Existing preferences file found, will not overwrite.
Traceback (most recent call last):
  File "/usr/local/bin/dmenu_extended_run", line 11, in <module>
    dmenu_extended.run(debug)
  File "/usr/local/lib/python2.7/dist-packages/dmenu_extended.py", line 1119, in run
    cache = d.cache_load()
  File "/usr/local/lib/python2.7/dist-packages/dmenu_extended.py", line 510, in cache_load
    if self.cache_regenerate() == False:
  File "/usr/local/lib/python2.7/dist-packages/dmenu_extended.py", line 477, in cache_regenerate
    cache = self.cache_build()
  File "/usr/local/lib/python2.7/dist-packages/dmenu_extended.py", line 677, in cache_build
    binaries = self.scan_binaries()
  File "/usr/local/lib/python2.7/dist-packages/dmenu_extended.py", line 533, in scan_binaries
    for binary in os.listdir(path):
OSError: [Errno 2] No such file or directory: '/usr/lib/lightdm/lightdm'
```

**Comment by markjones112358** [comment]
I believe this issue has just been fixed by @Spotlight0xff. Thanks!
If you can confirm it is working, I'll close this issue.

**Comment by vanishing** [comment]
I can confirm my issue is fixed.

**Comment by javaguirre** [comment]
For me It works too, sorry It took so long.
