### ISSUE TITLE
Why are you using /tmp/dmenuEextended_shellCommand.sh?

### ISSUE THREAD

**Issue by Tux1c** [markjones112358/dmenu-extended#16]
Hi,

So, I've seen that you are using  /tmp/dmenuEextended_shellCommand.sh to execute commands with the terminal.
However, atleast on my system, it doesn't work :\
I have no permission to execute that script, and any commands with ; or ;; at the end simply fail to execute.

Wouldn't it be easier to use ~/.dmenuExtended_Command.sh or something?

ls -l gives me that:
-rwxr-xr-x 1 yan  yan       57 27.02.2015 00:19 dmenuEextended_shellCommand.sh*

**Comment by markjones112358** [comment]
Hi Tux1c,
You're quite right. After a bit of reading up on the subject it seems that setting `/tmp` as non-excutable is a security precaution. I've updated dmenu-extended so by default it places the shellCommand script where you mentioned, but also added an entry into the configuration file called "path_shellCommand" that can be set manually.
I hope this fixes your problem; let me know.

**Comment by Tux1c** [comment]
@markjones112358 ,

I completely forgot I set noexec on /tmp ><, but yeah, your latest update fixed the issue, thanks!

Now, after I can test with my terminal, I'm going to finish my extension to the package manager plugin so it will support portage (gentoo and funtoo).

Closing this now :)

**Comment by markjones112358** [comment]
Cool, support for a new package manager would be great!
