### ISSUE TITLE
Most used at top

### ISSUE THREAD

**Issue by andreimarcu** [markjones112358/dmenu-extended#19]
First of all, thank you for dmenu-extended it's awesome and very useful.

I was wondering if you'd consider pushing the most used commands at the top, even and especially when searching for a program, no matter how many times I pick it, the next time I search for it I will still have to go down a few places or write its more letter of its name.

Thanks

**Comment by markjones112358** [comment]
Hi there, glad you're enjoying it.
That's a tricky one. This feature isn't something that I would personally want, but there may be others who may want this feature so it is worth considering.

One problem I see is that the cache will need to be altered each time the menu is accessed, which is likely to slow things down for those users with large caches.
It could just be a matter of recording the command frequency on execution and sorting each time the menu is opened, or storing and sorting on execution (maybe in a different thread).

I'll keep thinking about this and if I get some time I'll take a stab at it.

**Comment by nabsiddiqui** [comment]
For what it's worth, I think this would be a great feature if possible to add.

**Comment by nabsiddiqui** [comment]
Also, you could set up a txt file with the 100-200 most frequent commands and read those first before executing the rest of the search on files, etc.  

There may be some slow down, but you would probably speed things up since you are only searching through the 100-200 most frequent that people use and simply rebuilding that list if the command is not on there.  This way, people that have large caches would probably not notice the slow down as much if their frequent commands pop up earlier.

**Comment by markjones112358** [comment]
Hi nabsiddiqui,
Thanks for your suggestion. Seems as you are now the second person who would find this feature useful I will put some more thought into it.
Watch this space...

**Comment by nabsiddiqui** [comment]
There are two possible solutions for dmenu itself here:

[](https://faq.i3wm.org/question/6299/repeat-or-history-for-dmenu-commands.1.html)

[](https://github.com/manjaro/packages-community/blob/master/dmenu-manjaro/dmenu_recency)

In addition, I haven't tried it yet, but does dmenu_extended_run work with rofi?  I haven't tried it yet, but Rofi has the ability to save the 25 most recent commands.  

In the mean time, I have gotten used to creating aliases that are my most used commands.  It works pretty well for the time being, but it is a little tedious adding them manually.

**Comment by markjones112358** [comment]
Hi guys,
I have just pushed some changes that now allow you to have the most frequently used commands placed at the top of the menu (under the plug-ins). To enable this feature, pull the latest version of dmenu_extended and edit the preferences file. Set the following parameter (creating it if it does not already exist) as such:

    `"frequently_used": 25,

This will mean the menu will now show a maximum of 25 of your most used items, sorted so the most used appears at the top. Setting it to 0 will turn the feature off, and any other number with vary the number of items shown.

As always - any questions or comments are much appreciated.
Let me know if this is, or isn't, what you wanted.

-Mark

**Comment by nabsiddiqui** [comment]
This works great.  Thank you so much for this!  I have set it to 100 and it works amazingly well.
