### ISSUE TITLE
Can't build cache

### ISSUE THREAD

**Issue by AcarBurak** [markjones112358/dmenu-extended#22]
python -c "import dmenu_extended
> dmenu_extended.dmenu().cache_build()"
Setting up dmenu-extended prefs files...
Plugins directory exists - skipped
Cache directory exists - skipped
prefs directory exists - skipped
Existing preferences file found, will not overwrite.
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/usr/lib/python3.5/site-packages/dmenu_extended.py", line 668, in cache_build
    applications = self.scan_applications()
  File "/usr/lib/python3.5/site-packages/dmenu_extended.py", line 555, in scan_applications
    for line in f.readlines():
  File "/usr/lib/python3.5/codecs.py", line 706, in readlines
    return self.reader.readlines(sizehint)
  File "/usr/lib/python3.5/codecs.py", line 615, in readlines
    data = self.read()
  File "/usr/lib/python3.5/codecs.py", line 501, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd9 in position 22: invalid continuation byte

**Comment by markjones112358** [comment]
Hi, sorry for the delayed response.
This issue is occurring frequently with dmenu-extended users so I will be looking into this.
Hopefully sometime during the next week I'll get time to sort this out once and for all.
I'll keep you updated.
Thanks for trying dmenu-extended.

**Comment by AcarBurak** [comment]
Thank you.

**Comment by markjones112358** [comment]
Hi AcarBurak, guiguid just merged a change that will probably fix your problem.
Could you try out the latest version and let me know if the issue has gone?

**Comment by AcarBurak** [comment]
Works, thank you.
