### ISSUE TITLE
Fonts and size

### ISSUE THREAD

**Issue by chiffon-rouge** [markjones112358/dmenu-extended#24]
With the latest commit dmenu doesn't seem to honor the value given in the config anymore, which worked fine before. I have terminus set as font and 12 as font size and neither font nor size seem to change from a set standard value no matter what I chose. It shows a different font and the a much too big size when I run dmenu-extended. I tried directly editing the value in the "dmenu_extended.py" file but that didn't do the trick either.

**Comment by markjones112358** [comment]
Hi,
Can you run xfontsel and under the 'fmly' dropdown can you select terminus from there?

**Comment by chiffon-rouge** [comment]
Yes, I can.

**Comment by markjones112358** [comment]
Hi Chiffon.
Hey, I apologise for the poor response time - I'm super busy at the moment.
I can't see how that specific commit is causing your font selection to be ignored and I can't reproduce your issue.
If anyone else is having this problem and is reading this, please let me know.
Chiffon - could you paste your dmenuExtended_preferences.txt here?
Also, if you add a new item to the menu (`+random`), does it show up in the menu?
If it doesn't, I'm thinking dmenu_extended may not be loading your preferences file at all.

**Comment by chiffon-rouge** [comment]
Hey, it's no big deal, really. I have to admit I'm not as thorough at troubleshooting as I could be with this issues because otherwise it works like it used to be. Right now it's only a cosmetic issue.

It loads the file as, for example, when I change the colors it works. My config is as follows:

```python
{
    "alias_applications": false,
    "aliased_applications_format": "{name} ({command})",
    "exclude_items": [],
    "filebrowser": "xdg-open",
    "fileopener": "xdg-open",
    "filter_binaries": false,
    "follow_symlinks": false,
    "ignore_folders": [],
    "include_applications": true,
    "include_binaries": true,
    "include_hidden_files": false,
    "include_hidden_folders": false,
    "include_items": [],
    "indicator_alias": "#",
    "indicator_edit": "*",
    "indicator_submenu": "->",
    "menu": "dmenu",
    "menu_arguments": [
        "-b",
        "-i",
        "-nf",
        "#ffffff",
        "-nb",
        "#212629",
        "-sf",
        "#000000",
        "-sb",
        "#f2a18c",
        "-fn",
	"-*-terminus-medium-*-*-*-12-*-*-*-*-*-*-*"
    ],
    "path_shellCommand": "~/.dmenuEextended_shellCommand.sh",
    "scan_hidden_folders": false,
    "terminal": "urxvtc",
    "valid_extensions": [
        "py",
        "svg",
        "pdf",
        "txt",
        "png",
        "jpg",
        "gif",
        "php",
        "tex",
        "odf",
        "ods",
        "avi",
        "mpg",
        "mp3",
        "lyx",
        "bib",
        "iso",
        "ps",
        "zip",
        "xcf",
        "doc",
        "docxxls",
        "xlsx",
        "md",
        "sublime-project"
    ],
    "watch_folders": [
        "~/"
    ],
    "webbrowser": "xdg-open"
}

**Comment by chiffon-rouge** [comment]
I had to install Debian stable today because I ran into severe problems on testing out of my own stupidity. Long story short: Now it works like it did before and I'm not sure why it wasn't before. Maybe it had to with the dmenu package in testing dmenu-extended had as dependency? My guess is as good as anyone's.

**Comment by markjones112358** [comment]
That's good news!
