### ISSUE TITLE
Putting it on top of the sceen.

### ISSUE THREAD

**Issue by grapefroot** [markjones112358/dmenu-extended#26]
Hello.
Thank you for the awesome extension.
Is there any way to put it on top of the screen?(like ordinary dmenu).

**Comment by markjones112358** [comment]
Hi Grapefruit,
You sure can; edit your configuration and make the following changes to the "menu_arguments" field:

Default:

    "menu_arguments": [
        "-b", 
        "-i", 
        "-nf", 
        "#888888", 
        "-nb", 
        "#1D1F21", 
        "-sf", 
        "#ffffff", 
        "-sb", 
        "#1D1F21", 
        "-fn", 
        "-*-terminus-medium-*-*-*-14-*-*-*-*-*-*-*", 
        "-l", 
        "20"
    ], 

Top menu, single line:

    "menu_arguments": [
        "-i", 
        "-nf", 
        "#888888", 
        "-nb", 
        "#1D1F21", 
        "-sf", 
        "#ffffff", 
        "-sb", 
        "#1D1F21", 
        "-fn", 
        "-*-terminus-medium-*-*-*-14-*-*-*-*-*-*-*" 
    ], 

The arguments in that list are passed directly to dmenu so you can put any fields in there that is supported by the version of dmenu you're using. To find a list of options that dmenu supports, run the following command from the terminal:

    man dmenu
