### ISSUE TITLE
Directly search the internet

### ISSUE THREAD

**Issue by blacpythoz** [markjones112358/dmenu-extended#31]
Hello,
   Its great to see the new form of dmenu with added plugins. I really apreciate your work and I have been using it for my day to day life. 
 I was wonder if it is possible to directly search the internet with keybind. Currently, I have to run dmenu_extended_run and choose the third option with down key(which is far away) , select google and then search .. It will be nice if we can search directly with keybind like:

$ dmenu_extended_run --search google

Well, it will be really nice if you add the search result too in list format. 

Thanking You
Subash

**Comment by nabsiddiqui** [comment]
I had a similar issue and came up with a workaround:

1. Install the Internet Search Plugin and set Google to be your default web search(if I remember correctly, it already is)
2. In a text editor, open ~/.config/dmenu-extended/plugins/plugin_internetSearch.py
3. Edit the line that says title='Internet Search: ' right after class extension to say title= 'g: ' [The g for me stands for google]
4. Open dmenu_extended_run and rebuild the cache.
5. Now when you open up dmenu_extended_run the "g: " should be the first option.  Which means you can simply open up dmenu extended, and hit tab to begin searching.

Hope this helps.

**Comment by markjones112358** [comment]
Hi there,
I've updated dmenu_extended to give the functionality you're looking for (hopefully).
Once you've updated your dmenu_extended, refer to the README.md under the section "Advanced keybinds" for usage instructions.

Thanks Nabsiddqui, that is a nice workaround.

Let me know if you face any issues with the plugin or dmenu_extended.

**Comment by blacpythoz** [comment]
Thanks guys.. It works.

**Comment by markjones112358** [comment]
Great.
