### ISSUE TITLE
Running bash scripts with ";;"  gives an error.

### ISSUE THREAD

**Issue by bhainesva** [markjones112358/dmenu-extended#34]
For example, I'm trying to run a script ~/colors.sh. I first add it to the cache and then attempt to run with "~/colors.sh;;" from within dmenu_extended. This gives me the output

```
/home/username/.dmenuEextended_shellCommand.sh: line 2: -cd: command not found


Press enter to exit
```

The file dmenuEextended_shellCommand.sh contains

```
#! /bin/bash
-cd /home/username/colors.sh;
echo "

Press enter to exit";read var;
```

If I remove the "-cd " from [line 1257](https://github.com/markjones112358/dmenu-extended/blob/de860891df61ba3d5935966271e39721df3b4d52/dmenu_extended.py#L1257) it seems to work fine. 

As a side note dmenuE**e**xtended_shellCommand.sh was probably meant to be dmenuExtended_shellCommand.sh.

**Comment by markjones112358** [comment]
Hi there,
I've just pushed a change that will hopefully fix that issue.
Let me know it this solves it for you.

Thanks,
Mark

**Comment by bhainesva** [comment]
It works great now, thanks for the quick response!
