### ISSUE TITLE
Aliasing not working 

### ISSUE THREAD

**Issue by owen-young** [markjones112358/dmenu-extended#35]
I put "~/.bashrc" as my path_aliasFile and it isn't registering my aliases. I have alias_applications set to true. What more is there to do?

`
{
    "alias_applications": true,
    "alias_display_format": "{name}",
    "exclude_items": [],
    "filebrowser": "xdg-open",
    "fileopener": "xdg-open",
    "filter_binaries": true,
    "follow_symlinks": false,
    "frequently_used": 0,
    "ignore_folders": [],
    "include_applications": true,
    "include_binaries": true,
    "include_hidden_files": false,
    "include_hidden_folders": false,
    "include_items": [],
    "indicator_alias": "#",
    "indicator_edit": "*",
    "indicator_submenu": "->",
    "menu": "dmenu",
    "menu_arguments": [
        "-b",
        "-i",
        "-nf",
        "#888888",
        "-nb",
        "#1D1F21",
        "-sf",
        "#ffffff",
        "-sb",
        "#1D1F21",
        "-fn",
        "terminus",
        "-l",
        "20"
    ],
    "path_aliasFile": "~/.bashrc",
    "path_shellCommand": "~/.dmenuEextended_shellCommand.sh",
    "prompt": "Open:",
    "scan_hidden_folders": false,
    "terminal": "xterm",
    "valid_extensions": [
        "py",
        "svg",
        "pdf",
        "txt",
        "png",
        "jpg",
        "gif",
        "php",
        "tex",
        "odf",
        "ods",
        "avi",
        "mpg",
        "mp3",
        "lyx",
        "bib",
        "iso",
        "ps",
        "zip",
        "xcf",
        "doc",
        "docxxls",
        "xlsx",
        "md",
        "html",
        "sublime-project"
    ],
    "watch_folders": [
        "~/"
    ],
    "webbrowser": "xdg-open"
}
`

This is my dmenuExtended_preferences.txt. Should I change something within? Should I uninstall the old dmenu? All help is appreciated. Thanks.

**Comment by nabsiddiqui** [comment]
Did you rebuild the cache afterwards?

**Comment by nabsiddiqui** [comment]
Did you rebuild the cache afterwards?

**Comment by owen-young** [comment]
I did not but I will do that. Thanks.

**Comment by owen-young** [comment]
Ok, I rebuilt the cache but the aliases do not launch anything. They have the '#' I set in the config, but when selected and confirmed, nothing is launched.

**Comment by markjones112358** [comment]
Hi owen,
Could you paste the relevant alias line from your `.bashrc` file in here for us to see?

**Comment by owen-young** [comment]
None of the aliases work, but I will put my .bashrc here. 

`#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls -a --color=auto'
alias sudo='sudo '
alias emacs='emacsclient -nc --alternate-editor='''
alias steam='STEAM_RUNTIME=0 steam'
alias update='yaourt -Syua'
alias book='epdfview Precalculus1.pdf'
alias what_is_the_best_emoticon_in_the_entire_world='python best_emote.py'
PS1='[\u@\h \W]\$ '
export VISUAL="emacsclient -nc --alternate-editor=''"
export EDITOR="nano"
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. /usr/lib/python3.5/site-packages/powerline/bindings/bash/powerline.sh
`

Some applications aren't showing up at all either, such as wicd-client. I have to type it all in manually in order to launch it.

**Comment by owen-young** [comment]
nm-applet isn't showing up either, even after rebuilding the cache.

**Comment by markjones112358** [comment]
Hi Owen,
Sorry for the  delayed response.
I've just created a file containing the contents of your .bashrc file and pointed my configuration to it

    "path_aliasFile": "~/.bashrc"

After rebuilding the cache, each of the items appears in the cache as expected. At this point I am unable to reproduce the issue you are having.

As for the issue of "Some applications aren't showing up at all either", do these applications have binaries installed in your system path? I assume they do if you're able to type them in and they launch.

This is sounding like your cache isn't rebuilding properly.

Could you run and post the output of:

    dmenu_extended_run --debeg "rebuild cache"

Thansk.

**Comment by owen-young** [comment]
Running that command outputs nothing.

**Comment by markjones112358** [comment]
Sorry, typo in command. Try this

    dmenu_extended_run --debug "rebuild cache"

**Comment by owen-young** [comment]
```
Debugging enabled
Launch arguments: ['rebuild cache']
Frequently used items cache does not exist, will return nothing
Opening cache at /home/owen/.config/dmenu-extended/cache/dmenuExtended_plugins.txt
Opening cache at /home/owen/.config/dmenu-extended/cache/dmenuExtended_all.txt
Menu bypassed with launch argument: rebuild cache
First menu closed with user input: rebuild cache
Loading plugins
This command is not related to a plugin
Converting 'rebuild cache' into its aliased command
No suitable candidate was found
Done!
Watch folders:
Loading the list of folders to be excluded from the index...
Done!
Excluded folders:
First 5 items: 
[]
0 ignore_folders loaded in total

Indexing will follow linked folders
Scanning files and folders, this may take a while...
Opening alias file
Loading available plugins...
Loading plugins
Done!
Plugins loaded:
First 5 items: 
['-> Settings']
1 loaded in total

Done!
Cache building has finished.

```

**Comment by owen-young** [comment]
Yes, but, yet again, nothing launches.

**Comment by markjones112358** [comment]
Okay, you didn't say the items in your alias file are appearing in dmenu_extended. So it is picking them up.
What happens when you open a terminal and execute the following command:

    epdfview Precalculus1.pdf

**Comment by owen-young** [comment]
Sorry, that issue was fixed after I rebuilt the cache, so it is picking them up now.  Typing that command launches the alias I have, however, when I type "epdfview" the only thing that comes up is "#ePDFViewer" instead of the name of the actual application. Strange, but it still works. I thought the "#" was only for aliases, as specified in my config file.

**Comment by markjones112358** [comment]
Great, glad to hear it.
You're most probably seeing ePDFViewer as you have

    "include_applications": true,
    "alias_applications": true

in your configuration file, so it's picking up the name from the application's .desktop file.
The alias indicator,  which is set as # in your config, will be applied to any alias - including from .desktop files. If you don't want the applications aliased but still want the menu  to scan for applications, set this in your configuration file:

    "alias_applications": false
