### ISSUE TITLE
History feature

### ISSUE THREAD

**Issue by edi9999** [markjones112358/dmenu-extended#36]
In many line based programs (readline mostly), you can navigate the history of previous commands with Ctrl-p and Ctrl-n (or the arrow keys)

In dmenu-extended, I sometimes want to reexecute the same command that I executed last time.

Since arrow keys and Ctrl-p/Ctrl-n do the same thing (navigate between the choices), I propose that we use arrow keys for choice navigation and Ctrl-p/Ctrl-n for history navigation.

Would you be interested in implementing that ? If you don't have time to implement it, would you be accepting a merge request for that change. If yes, can you please pinpoint a bit where this change should be done ?

Thanks in advance !

**Comment by markjones112358** [comment]
Hi Edi,
One issue I see here is that dmenu is handling the direct input from the user, dmenu_extended is simply generating the menus and populating the lists (and handling the commands that dmenu returns). With this comes the limitation of separating specific keybindings by function. However, implementing a history feature would be quite simple as previous usage is already recorded for the "most used at top" feature.

I am happy to accept a merge request for any new features provided they do not interfere with the normal operation of the program.

Thanks for your suggestion and for using dmenu_extended.

-Mark

**Comment by edi9999** [comment]
Ok, I don't think it is possible to add the history feature from here. 

SInce I'm already using fzf as my fuzzy finder in other programs, I just decided to use that instead of the dmenu in my menu config.

fzf provides history with `C-p` and `C-n` when passing the --history flag

Here's my `~/.config/dmenu-extended/config/dmenuExtended_preferences.txt`

```
{
    "alias_applications": false,
        "alias_display_format": "{name}",
        "exclude_items": [],
        "filebrowser": "xdg-open",
        "fileopener": "xdg-open",
        "filter_binaries": true,
        "follow_symlinks": false,
        "frequently_used": 20,
        "ignore_folders": [],
        "include_applications": true,
        "include_binaries": true,
        "include_hidden_files": false,
        "include_hidden_folders": false,
        "include_items": [
            "htop"
        ],
        "indicator_alias": "",
        "indicator_edit": "*",
        "indicator_submenu": "->",
        "menu": "gfzf",
        "menu_arguments": [],
        "path_aliasFile": "",
        "path_shellCommand": "~/.dmenuEextended_shellCommand.sh",
        "prompt": "Open:",
        "scan_hidden_folders": false,
        "terminal": "xfce4-terminal",
        "valid_extensions": [
            "py",
        "svg",
        "pdf",
        "txt",
        "png",
        "jpg",
        "gif",
        "php",
        "tex",
        "odf",
        "ods",
        "avi",
        "mpg",
        "mp3",
        "lyx",
        "bib",
        "iso",
        "ps",
        "zip",
        "xcf",
        "doc",
        "docxxls",
        "xlsx",
        "md",
        "html",
        "sublime-project"
            ],
            "watch_folders": [
                "~/"
            ],
            "webbrowser": "xdg-open"
}
```

and here's the gfzf script : 

```
#!/bin/bash

cat >/tmp/fzfin

delay=0.05
pidfile=$(mktemp)

new_array=()
strip=0
for value in "$@"
do
	[[ $value = "-p" ]] && strip=2
	[[ "$strip" = "0" ]] && new_array+=($value)
	[[ "$strip" -gt "0" ]] && ((strip=strip-1))
done
array=("${new_array[@]}")
unset new_array

xfce4-terminal --title gfzf --fullscreen -x bash -i -c "echo \$$>$pidfile; cat /tmp/fzfin | fzf "${array[@]}" | tee /tmp/fzfout"

until [ -s "$pidfile" ]
do
	sleep "$delay"
done

terminalpid=$(cat "$pidfile")
rm "$pidfile"

while ps -p "$terminalpid" > /dev/null 2>&1
do
	sleep $delay
done

rm /tmp/fzfin
cat /tmp/fzfout
rm /tmp/fzfout
```

The only thing I didn't understand is what the -p option is used for. Is is just used for rendering, or is they any other use ?

**Comment by edi9999** [comment]
I'm closing this since I don't think it is the scope of this project to implement history in the keybindings.
