### ISSUE TITLE
cache takes very long time with many dotfiles

### ISSUE THREAD

**Issue by edi9999** [markjones112358/dmenu-extended#37]
I have a very huge amount of hidden files : about 400 000. 

Caching the files takes an infinite time to complete (it is running for more than an hour now)

If I change the code like this by adding a print(root)

```
        for watchdir in watch_folders:
            for root, dirs , files in os.walk(watchdir, followlinks=follow_symlinks):
                dirs[:] = [d for d in dirs if os.path.join(root,d) not in ignore_folders]
                print(root)
                if self.prefs['scan_hidden_folders'] or root.find('/.')  == -1:
                    for name in files:
                        if self.prefs['include_hidden_files'] or name.startswith('.') == False:
                            if valid_extensions == True or os.path.splitext(name)[1].lower() in valid_extensions:
                                filenames.append(os.path.join(root,name))
                    for name in dirs:
                        if self.prefs['include_hidden_folders'] or name.startswith('.') == False:
                            foldernames.append(os.path.join(root,name) + '/')
```

I see that all files are parsed recursively.
I have 'scan_hidden_folders' set to false.

I think the problem comes from the fact that os.walk is recursive, so it can be very slow since it will open all files, even if they are hidden. 

For example, it will open 

```
/home/edgar/Documents/articles/.git/objects/3b
/home/edgar/Documents/articles/.git/objects/4a
/home/edgar/Documents/articles/.git/objects/4b
/home/edgar/Documents/articles/.git/objects/4c
/home/edgar/Documents/articles/.git/objects/4d
/home/edgar/Documents/articles/.git/objects/4e
/home/edgar/Documents/articles/.git/objects/4f
```

I think by using `os.listdir(path)` and doing the recursion inside python, we would get a huge performance benefit.

**Comment by markjones112358** [comment]
Hi Edi,
I see what you mean and had a play around this morning with an alternative idea:

        for watchdir in [x for x in watch_folders if x != '']:
            tmp = subprocess.check_output(['find', watchdir]).split("\n")
            if self.prefs['include_hidden_files'] == False:
                foldernames = foldernames + list(filter(lambda x: x.find("/.") == -1, tmp))
                # print(foldernames)
            else:
                foldernames = foldernames + tmp

        for ignore_folder in ignore_folders:
            length = len(ignore_folder)
            foldernames = [x for x in foldernames if x[:length] != ignore_folder]

This makes use of the superfast `find` command, but I don't have a way to separate out folders  from files so it ended up not being much help (although it was about four times faster than os.walk).

At the moment I don't have the time to implement a custom folder walking function to test it, but am curious to see what the speed difference would be. If you've got the time and want to tackle that - please share your findings.

The original code isn't too bad as the next statement after your `print` statement checks to see if it's in a hidden folder. If it is it drops out of that loop and continues. So yes - it's still traversing folders under hidden folders, but it's ignoring the files and subfolders in those locations. This would only be a problem if you have a huge number of hidden *folders* as opposed to *files*; which you most likely wont.

As for slow cache building, make sure you have the follow_symlinks disabled as that can cause an infinite loop if there is a link to home buried in a folder somewhere.

**Comment by markjones112358** [comment]
I believe you solved this issue with your finding that walk was not honouring the removal of dot folders from the walk list. I'll close this issue now, but if you don't think it has been solved I can reopen it. Thanks again for your improvements to dmenu-extended.

**Comment by edi9999** [comment]
Yes this issue can ce closed !
