### ISSUE TITLE
Only search .desktop files?

### ISSUE THREAD

**Issue by nabsiddiqui** [markjones112358/dmenu-extended#39]
I would like to only be able to search only .desktop files, but it seems that they do not pick up properly.  For instance, I have a google-chrome.desktop file and I set the flag in the desktop file to be --force-device-scale-factor=1.3(for my monitor).  See here: https://major.io/2015/06/10/chrome-43-stuck-in-hidpi-mode/

If I launch this through xdg or through another window manager it picks up the settings, but it does not pick up the setting in dmenu extended.

**Comment by markjones112358** [comment]
Hi nabsiddiqui,
I just had a play around with that and I'd say you haven't rebuilt your cache since updating that .desktop file. Dmenu-extended parses the .desktop files at `cache build` time and adds what it finds there to its internal alias caching - so that needs to be updated.

Let me know if that fixes your issue.

**Comment by nabsiddiqui** [comment]
Sorry for the confusion.  I figured out what was going on.  I did not have the "alias applications" settings set to true.  As a result, when I was opening google chrome it was just opening the binary and not the actual desktop file.  

I don't want to start a new issue for this, but is there a way to clear the frequently used items by hand or maybe even clear the last few items(like 10 or 15).  Often, if I launch an application or type something incorrectly, it will continue to show up.  Or maybe something that colors the frequently used items differently than the regular ones?

**Comment by nabsiddiqui** [comment]
Sorry for the confusion.  I figured out what was going on.  I did not have the "alias applications" settings set to true.  As a result, when I was opening google chrome it was just opening the binary and not the actual desktop file.  

I don't want to start a new issue for this, but is there a way to clear the frequently used items by hand or maybe even clear the last few items(like 10 or 15).  Often, if I launch an application or type something incorrectly, it will continue to show up.  Or maybe something that colors the frequently used items differently than the regular ones?

**Comment by markjones112358** [comment]
No problem.
As for your question of hand editing the frequently used items - the file you are looking for is:

    ~/.config/dmenu-extended/cache/dmenuExtended_frequentlyUsed_frequency.json

That file contains the name and total usage count of each item in the menu. You can clear entries entirely or manually change their usage count by hand. The changes wont show up in the menu until you next launch something through the menu, at which point the accompanying file `dmenuExtended_frequentlyUsed_ordered.json` gets generated (but don't edit that file as your changes will be overwritten).

Hope that helps.
