### ISSUE TITLE
'desktop' entries do not open any more

### ISSUE THREAD

**Issue by helge000** [markjones112358/dmenu-extended#41]
I was running 56b9f6f for some time now and recently started pulling the new versions. I noticed desktop entries were not working any more; they just do not open.

I did a bisect, which points to 5aeafa3f9f3cb4665a23d56b2a908afca1c48ef2 :

```
5aeafa3f9f3cb4665a23d56b2a908afca1c48ef2 is the first bad commit
commit 5aeafa3f9f3cb4665a23d56b2a908afca1c48ef2
Author: Mark H. Jones <markjones112358@gmail.com>
Date:   Mon Jun 6 17:36:00 2016 +1200

    Rewrote adding and removing entry logic

:100755 100755 c401e08fe3cb609b6a61b9a86d0273b076258d17 4aac3bae58feb52f10c38225575e9ffe35c1e8b4 M  dmenu_extended.py
```

**Comment by nabsiddiqui** [comment]
I am also having a problem with .desktop entries that open terminal applications.  For instance, opening my vim.desktop file seems to not launch a new terminal.  It works correctly in my file manager.  Here is the .desktop file:

`TryExec=vim
Exec=vim %F
Terminal=true
Type=Application
Icon=gvim
Categories=Utility;TextEditor;
StartupNotify=false
MimeType=text/english;text/plain;text/x-makefile;text/x-c++hdr;text/x-c++src;text/x-chdr;text/x-csrc;text/x-java;text/x-moc;text/x-pascal;text/x-tcl;text/x-tex;application/x-shellscript;text/x-c;text/x-c++;
`

**Comment by markjones112358** [comment]
Hello to you both,
Sorry for the delay with looking into the issues raised.
Would you both be able to pull the latest version of dmenu-extended, rebuild your cache and test to see if the issues have been fixed?

**Comment by helge000** [comment]
+1
Seem to work now ( though strangely gedit does not work)

**Comment by markjones112358** [comment]
That's odd. I've just run it on my end and gedit is opening. I've made another couple of changes to how applications are aliased from .desktop files that might be worth you trying.

**Comment by nabsiddiqui** [comment]
I am still running into the same problem.  I am opening a Markdown file in vim dmenu extended, but it seems to run a terminal very quickly and then close.  It opens properly both when running through the terminal and through Caja(my file manager).  I can associate it to a new non-terminal application, and it works correctly.

**Comment by helge000** [comment]
> That's odd. I've just run it on my end and gedit is opening. I've made another couple of changes to how applications are aliased from .desktop files that might be worth you trying.

That did it. Now even gedit is working. Thanks!

**Comment by nabsiddiqui** [comment]
I think there is a problem with the aliasing of applications in the new version?  Perhaps a spacing issue?  I am not sure.  I can open them up unaliased.  It only happens on certain applications.  I didn't have this problem in the previous versions.

**Comment by markjones112358** [comment]
I'm having trouble reproducing the problem you describe. 
Could you confirm that you've rebuilt the cache since upgrading or changing any settings?
Also, could you give the name of a program that's not responding and what you have set for:

    "alias_applications": ?, 
    "alias_display_format": ?, 

What would also be really interesting is the relevant element in:

    ~/.config/dmenu-extended/cache/dmenuExtended_aliases_lookup.json

Cheers

**Comment by nabsiddiqui** [comment]
Sorry it has taken me so long to respond.  I have been bombarded at work.  Here is the settings that I currently have:

```
"alias_applications": true, 
    "alias_display_format": "{name}", 
    "exclude_items": [], 
    "filebrowser": "xdg-open", 
    "fileopener": "xdg-open", 
    "filter_binaries": false, 
    "follow_symlinks": false, 
    "frequently_used": 100, 
    "ignore_folders": [], 
    "include_applications": true, 
    "include_binaries": false, 
    "include_hidden_files": false, 
    "include_hidden_folders": false, 
```

I think it has something to do with the default application having an argument built into it.  For instance, to open a file in Caja(file manager), you have to send the argument caja --no-desktop.  I often get "caja --no-desktop not found."  It is intermittent, however, some files do open.  This is how the entry is in the .json file.

```
[
        "Caja", 
        "caja --no-desktop"
    ], 
 ```

I also open up PDFs with zathura, and they sometimes launch "Gnome Software Center."  I have no idea why that is.  Other pdfs open fine.

**Comment by markjones112358** [comment]
Not a problem, I'm in the same boat with time and working. I've made a change that I hope will fix the issue you're having. Please try pulling the latest version and let me know if the problem goes away.

**Comment by markjones112358** [comment]
Assuming this problem has been solved. Create a new issue if this is not the case.
