### ISSUE TITLE
Changing window's size and exit key

### ISSUE THREAD

**Issue by mimf** [markjones112358/dmenu-extended#42]
Hello,

I recently started using dmenu-extended and I'm quite pleased with it! I've two questions however:

- Is it possible to change the size of the window? By default, it seems to be half the vertical size of the screen. I would like to change this. Is it possible? (I find it too big);

- Is it possible to make it so the shortcut to open dmenu-extended, closes it if it's already opened? I don't like having to type esc to close it;

- Is it possible to change the position of the window? For example, change it to the top (instead of bottom), or to the mid of the screen..

Also, I find that there's slight delay in opening dmenu-extended after pressing the shortcut. It's a very small delay, but it's noticeable. Anything I can do to improve opening time?

Sorry for nitpicking! Dmenu-extended is awesome, thank you! 

**EDIT:** I've managed to change the verical size of the window by changing one of the "menu-arguments".

**Comment by blacpythoz** [comment]
just remove the -b option from the menu-arguments to place it in top.

**Comment by mimf** [comment]
Thank you for the reply @blacpythoz. I indeed found out most of my questions by reading the manual of dmenu. Creating this issue was a little bit hasty of me, I apologize.

I still find that dmenu-extended has a slow start-up time, but it's probably normal and not easy to make it faster..

**Comment by blacpythoz** [comment]
You can also add some directory like cache and local to the exclude list to make a bit faster.

**Comment by markjones112358** [comment]
Closing as you've solved the issue described in the title.
If the menu is taking a while to load, have a look through the menu and see if there are folders with a ton of files being cached that aren't useful. I ran into this after downloading test datasets with thousands of files.
If you do have something like this being indexed and you don't need these items to be cached, add the relevant paths to:

    "ignore_folders": [], 

in the preferences file. Then rebuild your cache and depending on how many entries have been removed, you should see anywhere from not much improvement in load time to almost instant load time.
