### ISSUE TITLE
Problems with umlauts/other special characters

### ISSUE THREAD

**Issue by vestingz** [markjones112358/dmenu-extended#44]
dmenu-extended correctly indexes files which names contain characters like ö, ä, ü, §, but seems to incorrectly pass those paths to xdg-open, so nothing happens when opening these files via dmenu-extended.

**Comment by markjones112358** [comment]
Hi there,
I've made some changes which I believe solve the problem you are having. Would you try updating your dmenu-extended and seeing if it works for you now?

Thanks

**Comment by vestingz** [comment]
Thank you very much! It does indeed solve the problem, although only for files newly added to the index. Files which have been indexed before still cannot be opened.

**Comment by markjones112358** [comment]
That's weird.
Have you tried rebuilding the cache?
If it still doesn't work: are the items that aren't opening ones that you've added to the cache manually (custom entries)?
If not, could you post an example of an item not opening?

**Comment by vestingz** [comment]
Yip, rebuild the cache but problem persists. I just noticed that umlauts in folder paths don't matter, only in filenames. There are no manual entries to the cache.
Please find an example file attached.
[1983 - BVerfG - Volkszählungsurteil - 1983.pdf](https://github.com/markjones112358/dmenu-extended/files/694757/1983.-.BVerfG.-.Volkszahlungsurteil.-.1983.pdf)

**Comment by markjones112358** [comment]
Great, thanks for that. I've pushed a change that should fix this. Hopefully, after updating, everything is working correctly for you now?

**Comment by vestingz** [comment]
Great, works like a charm, thanks a ton! :)
