### ISSUE TITLE
Rofi integration?

### ISSUE THREAD

**Issue by vestingz** [markjones112358/dmenu-extended#46]
Just tried calling dmenu_extended.py as rofi mode (rofi -show dm -modi dm:~/git/dmenu_extended/dmenu_extended.py), which returns the following error: `from: can't read /var/mail/__future__`
Any ideas?

**Comment by markjones112358** [comment]
The readme has a snippet on the configuration settings used to open
dmenu-extended with rofi (under 'Running Dmenu-extended with Rofi'). Have a
go at that and let me know.

**Comment by vestingz** [comment]
Of course it's working now :) Sorry for this useless question!

**Comment by markjones112358** [comment]
Not a problem, glad it's going.
