### ISSUE TITLE
OSError: [Errno 2] No such file or directory on Ubuntu

### ISSUE THREAD

**Issue by GijsTimmers** [markjones112358/dmenu-extended#49]
Running `dmenu-extended`, latest git pull, on awesome in ubuntu 17.04

Getting this error.
```
$ dmenu_extended_run --debug
Debugging enabled
Launch arguments: []
Frequently used items cache does not exist, will return nothing
Opening cache at /home/user/.config/dmenu-extended/cache/dmenuExtended_plugins.txt
Opening cache at /home/user/.config/dmenu-extended/cache/dmenuExtended_all.txt
First menu closed with user input: Chromium Web Browser (chromium-browser)
Loading plugins
This command is not related to a plugin
Converting 'Chromium Web Browser (chromium-browser)' into its aliased command
Chromium Web Browser (chromium-browser)
No suitable candidate was found
Executing user input as a command
Executing: Chromium Web Browser (chromium-browser)
Command converted into:
[u'Chromium', u'Web', u'Browser', u'(chromium-browser)']
Traceback (most recent call last):
  File "/usr/local/bin/dmenu_extended_run", line 7, in <module>
    dmenu_extended.run(*sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/dmenu_extended.py", line 1844, in run
    handle_command(d, out)
  File "/usr/local/lib/python2.7/dist-packages/dmenu_extended.py", line 1506, in handle_command
    d.execute(out)
  File "/usr/local/lib/python2.7/dist-packages/dmenu_extended.py", line 649, in execute
    return subprocess.call(command)
  File "/usr/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by markjones112358** [comment]
Hi there,
Try rebuilding your cache.
I see you're using a different alias display format: `"{name} ({command})"` as opposed to the default `"{name}"`.
I can reproduce this error by setting the alias_display_format to `"{name} ({command})"`, rebuilding the cache, then changing the alias_display_format back to `"{name}"` and attempting to run the Chromium Web Browser (chromium-browser).
Let me know if this doesn't fix your problem.

**Comment by GijsTimmers** [comment]
Thanks for getting back at me.

I could not fix the problem by changing the `alias_display_format` parameter and rebuilding the cache. The problem persisted.

I ended up backing up `~/.config/dmenu-extended/config/dmenuExtended_preferences.txt` and removing the `~/.config/dmenu-extended` directory, forcing dmenu to create new config (and cache?) files. This fixed the issue.

Comparing the old and new parameters with `vimdiff` did not show me anything out of the ordinary, so it must've been a problem with the cache, as you predicted.
