### ISSUE TITLE
Execute command in custom environment

### ISSUE THREAD

**Issue by vestingz** [markjones112358/dmenu-extended#52]
I can't get my head around a way to launch a command through dmenu_extended using a specific environment variable like this: env $VAR=<sth> command. Neither defining an alias nor a wrapper script would work with dmenu. Any tips?

**Comment by markjones112358** [comment]
Hi,
A wrapper script should do it. I just made a simple test case with the following bash scripts:

~/test1.sh

    echo $HOME
    echo $TEST

and a second, ~/test2.sh

    export TEST=goat
    sh ~/test1.sh

Then I give the second script execute permissions
`chmod +x test2.sh`
Set test to something distinctive that isn't goat
`export TEST=dog`

Run the test2 script through dmenu-extended with the double semi-colons so the resulting window stays open after execution (`/home/mark/test2.sh;;`) and the result I get is:

    /home/mark
    goat

If I run the same script directly I get

    /home/mark
    dog

Is that doing what you want?

**Comment by vestingz** [comment]
Thank you very much for your suggestion! The example worked as expected, however, i could not make it work with my scenario (starting libreoffice with a different GTK_THEME variable). The solution was finally to create a .desktop file and just exec env $VAR=VAL libreoffice --writer. Thanks again for your kind help :)
