### ISSUE TITLE
dmenu-extended and rofi

### ISSUE THREAD

**Issue by stef204** [markjones112358/dmenu-extended#54]
@markjones112358 

Is it possible to use dmenu-extended with rofi--but setting the number of lines somehow in the `"menu_arguments"` inside dmenuExtended_preferences.txt ?

I tried using this: `    "-theme-str '#listview { lines:20;}' -show drun"` for example.  This works on the cli but not as an argument inside the json file.

I also tried the simple `"-lines 20"` inside of `"menu_arguments"` either before or after `"-dmenu"` to no avail.

This feature would be helpful as I already run rofi as window switcher but only want just a few lines in that case.

OTOH, when using dmenu-extended, I want 20 lines or more (useful when scrolling through files). I have not found a way to have settings for opening rofi with a different number of lines (when using dmenu-extended) yet but it should be possible.

**Comment by markjones112358** [comment]
Hi there,
I've just had a play around and found that I could get `dmenu-extended` to open with `rofi` with a custom number of lines by having the following set in my preference file:

    "menu": "rofi",
    "menu_arguments": [
      "-dmenu",
      "-l",
      "5"
    ],

That would open with 5 line. I also tested with 1 and 10 which gave the result you were looking for.
Let me know if this works for you.

**Comment by stef204** [comment]
Works like a charm! Thank you.
Keep up the good work, this is an extremely useful utility.
